included:
  - UberGoCore

excluded:
  - UberGoCore/RxCLLocationManagerDelegateProxy.swift
  - UberGoCore/CLLocationManager+Rx.swift
  - UberGoCore/Reachability.swift
  - UberGoCore/ReachabilityService.swift

opt_in_rules:
  - empty_count
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - object_literal
  - number_separator
  - prohibited_super_call
  - fatal_error_message

disabled_rules:
  - nesting
  - force_cast
  - attributes
  - function_body_length
  
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?\.swift
                    \/\/  SwiftLint
                    \/\/
                    \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{2}\.
                    \/\/  Copyright © \d{4} Realm\. All rights reserved\.
                    \/\/
identifier_name:
  min_length: 2
  excluded:
    - id
line_length: 120
number_separator:
  minimum_length: 5
