included:
  - UberGo
  - UberGoCore
excluded:
  - UberGoCore/UberGoCoreTests
opt_in_rules:
  - attributes
  - empty_count
  - vertical_whitespace
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - switch_case_on_newline
  - conditional_returns_on_newline
  - switch_case_on_newline
  - first_where
line_length: 160

